const fs = require('fs');                                                                                                                                                                                                                                                                                                                                                           
const path = require('path');                                                                                                                                                                                                                                                                                                                                                       
const readline = require('readline');                                                                                                                                                                                                                                                                                                                                               
const {spawn} = require('node:child_process');                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                    
const rl = readline.createInterface({                                                                                                                                                                                                                                                                                                                                               
        input : fs.createReadStream('./output4-7-22.txt'),                                                                                                                                                                                                                                                                                                                          
        crlfDelay: Infinity,                                                                                                                                                                                                                                                                                                                                                        
});                                                                                                                                                                                                                                                                                                                                                                                 
const fileQueue = [];                                                                                                                                                                                                                                                                                                                                                               
let isProcessing = false;                                                                                                                                                                                                                                                                                                                                                           
function processNextFile() {                                                                                                                                                                                                                                                                                                                                                        
  if (fileQueue.length === 0) {                                                                                                                                                                                                                                                                                                                                                     
    isProcessing = false;                                                                                                                                                                                                                                                                                                                                                           
    return;                                                                                                                                                                                                                                                                                                                                                                         
  }                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                    
  isProcessing = true;                                                                                                                                                                                                                                                                                                                                                              
  const { audioPath, jsonPath } = fileQueue.shift();                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    
  console.log(`Processing file: ${audioPath} with JSON: ${jsonPath}`);                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                    
  const file_path = path.basename(audioPath);                                                                                                                                                                                                                                                                                                                                       
  const s3_path = `s3://homestarsyt/${file_path}`;                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                    
  console.log(`Downloading from ${s3_path}...`);                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                    
  const awsProcess = spawn('aws', ['s3', 'cp', s3_path, '.'], {                                                                                                                                                                                                                                                                                                                     
    stdio: 'inherit'                                                                                                                                                                                                                                                                                                                                                                
  });                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                    
  awsProcess.on('close', (code) => {                                                                                                                                                                                                                                                                                                                                                
    console.log(`aws s3 cp exited with code ${code}`);                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                    
    if (code === 0) {                                                                                                                                                                                                                                                                                                                                                               
      // Download successful                                                                                                                                                                                                                                                                                                                                                        
      console.log(`Download successful, now processing with redactaudio.js`);                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                    
      const child = spawn('node', [                                                                                                                                                                                                                                                                                                                                                 
        'redactaudio.js',                                                                                                                                                                                                                                                                                                                                                           
        '-a', audioPath,                                                                                                                                                                                                                                                                                                                                                            
        '-j', jsonPath                                                                                                                                                                                                                                                                                                                                                              
      ], {                                                                                                                                                                                                                                                                                                                                                                          
        stdio: 'inherit'                                                                                                                                                                                                                                                                                                                                                            
      });                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                    
      child.on('close', (childCode) => {                                                                                                                                                                                                                                                                                                                                            
        console.log(`Child process exited with code ${childCode}`);                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                    
        // Process the next file in the queue                                                                                                                                                                                                                                                                                                                                       
        processNextFile();                                                                                                                                                                                                                                                                                                                                                          
      });                                                                                                                                                                                                                                                                                                                                                                           
    } else {
           console.error(`Failed to download file: ${s3_path}`);
      // Continue with the next file even if this one failed
      processNextFile();
    }     
  });     
}         
          
let prev_line = null;
rl.on('line', (line) => {
  let len = line.split('.').length;
          
  if (len > 1) {
    if (line.split('.')[len - 1] === 'json') {
      const audioPath = path.resolve(prev_line);
      const jsonPath = path.resolve(line);
          
      // Add the file to the queue
      fileQueue.push({ audioPath, jsonPath });
      console.log(`Added to queue: Audio: ${audioPath}, JSON: ${jsonPath}`);
          
      // Start processing if not already processing
      if (!isProcessing) {
        processNextFile();
      }   
    }     
  }       
          
  prev_line = line;
});       
          
rl.on('close', () => {
  console.log('Input stream closed. Finishing remaining jobs in queue...');
  // The queue will continue processing until empty
});              